#端口号配置
server:
  port: 8080
#数据库连接配置
spring:
  profiles:
    active: common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/temp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1233

# JWT配置
jwt:
  secret: com.momo.security
  expiration: 21600000

# 项目配置
momo:
  login-url: /api/user/login

# mybatis-plus 配置
mybatis-plus:
  global-config:
    #驼峰下划线转换
    db-column-underline: true
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl